"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { COUNTRIES } from "@/lib/countries";
import { apiRequest } from "@/lib/api";
import { showToast } from "@/lib/toast";

type View = "dashboard" | "demandes" | "nouvelle" | "documents" | "paiements" | "profil" | "messages" | "verification";
type User = { id: string; email: string; firstName: string; lastName: string; phone?: string; country?: string; originCountry?: string; role?: string };
type DocumentItem = { id: string; name: string; mimeType: string; size: number; applicationId: string; createdAt: string };
type Payment = { id: string; provider: string; amount: number; currency: string; status: string; applicationId: string; createdAt: string };
type Application = { id: string; type: string; status: string; reference: string; createdAt: string; formData: Record<string, unknown>; documents: DocumentItem[]; payments: Payment[] };

const statuses: Record<string, string> = { DRAFT: "Brouillon", SUBMITTED: "Soumise", PAYMENT_PENDING: "En attente de paiement", PAID: "Payée", IN_REVIEW: "En vérification", APPROVED: "Validée", DELIVERED: "Émise", REJECTED: "Refusée", CANCELLED: "Annulée" };
const types: Record<string, string> = { AVI: "AVI", ADL: "ADL", CAMPUS_FRANCE: "Campus France", SCHOLARSHIP: "Bourse" };
const navigation: { id: View; label: string; icon: string }[] = [
  { id: "dashboard", label: "Tableau de bord", icon: "▦" }, { id: "demandes", label: "Mes demandes", icon: "☷" },
  { id: "nouvelle", label: "Nouvelle demande", icon: "▤" }, { id: "documents", label: "Mes documents", icon: "▱" },
  { id: "paiements", label: "Mes paiements", icon: "▭" }, { id: "profil", label: "Mon profil", icon: "♙" },
  { id: "messages", label: "Mes messages", icon: "✉" },
];

function initials(user: User) { return `${user.firstName[0] ?? ""}${user.lastName[0] ?? ""}`.toUpperCase(); }
function date(value: string) { return new Intl.DateTimeFormat("fr-FR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)); }
function amount(value: number, currency: string) { return new Intl.NumberFormat("fr-FR", { style: "currency", currency }).format(value / 100); }
function title(view: View) { return { dashboard: "Tableau de bord", demandes: "Mes demandes", nouvelle: "Nouvelle demande", documents: "Mes documents", paiements: "Mes paiements", profil: "Mon profil", messages: "Mes messages", verification: "Vérifier un document" }[view]; }

export default function Dashboard() {
  const [user, setUser] = useState<User | null>(null);
  const [token, setToken] = useState<string | null>(null);
  const [applications, setApplications] = useState<Application[]>([]);
  const [view, setView] = useState<View>("dashboard");
  const [mode, setMode] = useState<"login" | "register">("login");
  const [loading, setLoading] = useState(false);
  const [authFeedback, setAuthFeedback] = useState("");
  const [authError, setAuthError] = useState("");
  const [emailForResend, setEmailForResend] = useState("");
  const [resending, setResending] = useState(false);

  async function load(accessToken: string) {
    try { setApplications(await apiRequest<Application[]>("/applications", { headers: { Authorization: `Bearer ${accessToken}` } })); }
    catch { showToast("Impossible de charger vos demandes."); }
  }

  useEffect(() => {
    if (new URLSearchParams(window.location.search).get("mode") === "register") setMode("register");
    const savedToken = window.localStorage.getItem("gpi_access_token");
    const savedUser = window.localStorage.getItem("gpi_user");
    if (!savedToken || !savedUser) return;
    try {
      const saved = JSON.parse(savedUser) as User;
      if (saved.role === "ADMIN" || saved.role === "ADVISOR") {
        window.location.replace(saved.role === "ADMIN" ? "/admin" : "/conseiller");
        return;
      }
      setToken(savedToken); setUser(saved); void load(savedToken);
    }
    catch { window.localStorage.removeItem("gpi_access_token"); window.localStorage.removeItem("gpi_user"); }
  }, []);

  useEffect(() => {
    if (!token || !user) return;
    const heartbeat = () => void apiRequest("/auth/heartbeat", { method: "POST", headers: { Authorization: `Bearer ${token}` } }).catch(() => undefined);
    heartbeat();
    const interval = window.setInterval(heartbeat, 60_000);
    return () => window.clearInterval(interval);
  }, [token, user]);

  async function authenticate(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setAuthFeedback(""); setAuthError("");
    const form = event.currentTarget;
    const get = (name: string) => (form.elements.namedItem(name) as HTMLInputElement | HTMLSelectElement)?.value;
    const payload = mode === "login" ? { email: get("email"), password: get("password") } : { email: get("email"), password: get("password"), firstName: get("firstName"), lastName: get("lastName"), phone: get("phone"), country: get("country"), originCountry: get("originCountry") };
    try {
      setEmailForResend(payload.email ?? "");
      if (mode === "register") {
        const result = await apiRequest<{ message: string }>("/auth/register", { method: "POST", body: JSON.stringify(payload) });
        setAuthFeedback(result.message);
        setMode("login");
        return;
      }
      const result = await apiRequest<{ accessToken: string; user: User }>(`/auth/${mode}`, { method: "POST", body: JSON.stringify(payload) });
      setToken(result.accessToken); setUser(result.user); window.localStorage.setItem("gpi_access_token", result.accessToken); window.localStorage.setItem("gpi_user", JSON.stringify(result.user));
      if (result.user.role === "ADMIN" || result.user.role === "ADVISOR") {
        window.location.replace(result.user.role === "ADMIN" ? "/admin" : "/conseiller");
        return;
      }
      void load(result.accessToken); setView("dashboard"); showToast(`Bienvenue ${result.user.firstName} ✓`);
    } catch (reason) { const message = reason instanceof Error ? reason.message : "Impossible de contacter le serveur."; setAuthError(message); showToast(`${message} ✗`); }
    finally { setLoading(false); }
  }

  async function resendVerification() {
    if (!emailForResend) return;
    setResending(true); setAuthError(""); setAuthFeedback("");
    try {
      const result = await apiRequest<{ message: string }>("/auth/resend-verification", { method: "POST", body: JSON.stringify({ email: emailForResend }) });
      setAuthFeedback(result.message);
    } catch (reason) { setAuthError(reason instanceof Error ? reason.message : "Impossible d’envoyer le lien."); }
    finally { setResending(false); }
  }

  function logout() { setUser(null); setToken(null); setApplications([]); window.localStorage.removeItem("gpi_access_token"); window.localStorage.removeItem("gpi_user"); showToast("Vous êtes déconnecté"); }
  if (!user) return <div><Auth mode={mode} setMode={(nextMode) => { setMode(nextMode); setAuthFeedback(""); setAuthError(""); }} loading={loading} onSubmit={authenticate} />{authError && <p role="alert" className="mx-auto mt-4 max-w-[560px] rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{authError}</p>}{authFeedback && <p role="status" className="mx-auto mt-4 max-w-[560px] rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{authFeedback}</p>}{mode === "login" && <div className="mx-auto mt-4 flex max-w-[560px] flex-wrap items-center justify-between gap-3 text-sm"><button type="button" disabled={!emailForResend || resending} onClick={resendVerification} className="font-medium text-slate hover:text-ink disabled:opacity-50">{resending ? "Envoi…" : "Renvoyer le lien de vérification"}</button><Link href="/reset-password" className="font-medium text-slate hover:text-ink">Mot de passe oublié ?</Link></div>}{mode === "register" && <p className="mx-auto mt-4 max-w-[560px] text-center text-xs text-slate">Les comptes administrateur sont créés et attribués séparément par l’équipe GPI.</p>}</div>;

  const counts = { total: applications.length, done: applications.filter((item) => ["APPROVED", "DELIVERED", "PAID"].includes(item.status)).length, active: applications.filter((item) => !["APPROVED", "DELIVERED", "REJECTED", "CANCELLED"].includes(item.status)).length, refused: applications.filter((item) => ["REJECTED", "CANCELLED"].includes(item.status)).length };
  const refresh = () => { if (token) void load(token); };
  return <div className="overflow-hidden rounded-[14px] border bg-[#f4f5fa] shadow-[0_20px_60px_-30px_rgba(15,27,51,.45)]" style={{ borderColor: "var(--line)" }}><div className="flex min-h-[720px] flex-col lg:flex-row">
    <aside className="flex w-full flex-col bg-ink text-paper lg:w-[246px] lg:flex-none"><div className="flex h-[72px] items-center border-b border-white/10 px-5"><div className="mr-2 flex h-9 w-9 items-center justify-center rounded-full bg-white/10 font-display font-bold text-red-2">G</div><span className="font-display text-lg font-bold">GPI <small className="block font-mono text-[8px] font-normal tracking-[.18em] text-white/50">ESPACE ÉTUDIANT</small></span></div><div className="flex items-center gap-3 border-b border-white/10 px-5 py-5"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-red font-bold">{initials(user)}</div><div className="min-w-0"><b className="block truncate text-sm">{user.firstName} {user.lastName}</b><span className="block truncate text-xs text-white/50">{user.email}</span></div></div><nav className="flex gap-1 overflow-x-auto p-3 lg:block lg:flex-1 lg:overflow-visible"><p className="hidden px-3 pb-2 pt-3 font-mono text-[10px] uppercase tracking-[.18em] text-white/40 lg:block">Demandes</p>{navigation.map((item) => <button key={item.id} onClick={() => setView(item.id)} className={`flex min-w-max items-center gap-3 rounded-lg px-3 py-3 text-left text-sm transition-colors lg:mb-1 lg:w-full ${view === item.id ? "bg-red font-semibold text-white" : "text-white/70 hover:bg-white/[.07] hover:text-white"}`}><span className="w-4 text-center text-base">{item.icon}</span>{item.label}</button>)}<div className="hidden border-t border-white/10 pt-3 lg:mt-4 lg:block"><button onClick={() => setView("verification")} className={`mb-1 flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm ${view === "verification" ? "bg-red font-semibold text-white" : "text-white/70 hover:bg-white/[.07]"}`}><span className="w-4 text-center">⌾</span>Vérifier un document</button><a href="/" className="flex items-center gap-3 rounded-lg px-3 py-3 text-sm text-white/70 hover:bg-white/[.07]"><span className="w-4 text-center">⌂</span>Site public</a></div></nav><button onClick={logout} className="hidden border-t border-white/10 px-6 py-5 text-left text-sm text-white/60 hover:text-white lg:block">↪ Déconnexion</button></aside>
    <main className="min-w-0 flex-1"><header className="flex h-[72px] items-center justify-between border-b bg-white px-5 lg:px-7" style={{ borderColor: "var(--line)" }}><div><b className="block text-sm uppercase tracking-wide">{title(view)}</b><span className="hidden text-xs text-slate-light sm:block">GPI — Espace étudiant</span></div><div className="flex items-center gap-4"><span className="text-lg text-slate-light">♧</span><div className="flex h-9 w-9 items-center justify-center rounded-full bg-red font-bold text-white">{initials(user)}</div></div></header><div className="p-5 lg:p-8">{view === "dashboard" && <Home user={user} applications={applications} counts={counts} onView={setView} />}{view === "demandes" && <Demandes applications={applications} onView={setView} />}{view === "nouvelle" && <NewRequest token={token} onDone={() => { setView("demandes"); refresh(); }} />}{view === "documents" && <Documents applications={applications} token={token} onUploaded={refresh} />}{view === "paiements" && <Payments applications={applications} />}{view === "profil" && <Profile user={user} />}{view === "messages" && <Messages token={token} />}{view === "verification" && <Verification />}</div></main>
  </div></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field block">{label}{children}</label>; }
function Auth({ mode, setMode, loading, onSubmit }: { mode: "login" | "register"; setMode: (value: "login" | "register") => void; loading: boolean; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void }) { return <div className="mx-auto max-w-[560px]"><div className="card"><div className="mb-6 flex gap-2 text-sm"><button onClick={() => setMode("login")} className={`flex-1 rounded-lg py-2.5 font-semibold ${mode === "login" ? "bg-ink text-white" : "border"}`}>Se connecter</button><button onClick={() => setMode("register")} className={`flex-1 rounded-lg py-2.5 font-semibold ${mode === "register" ? "bg-ink text-white" : "border"}`}>Créer un compte</button></div><form onSubmit={onSubmit} className="space-y-4">{mode === "register" && <div className="grid gap-4 sm:grid-cols-2"><Field label="Prénom"><input name="firstName" required /></Field><Field label="Nom"><input name="lastName" required /></Field></div>}<div className="grid gap-4 sm:grid-cols-2"><Field label="Email"><input name="email" type="email" required /></Field><Field label="Mot de passe"><input name="password" type="password" minLength={8} required /></Field></div>{mode === "register" && <><Field label="Téléphone"><input name="phone" required /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Pays de résidence"><select name="country" required defaultValue=""><option value="" disabled>Sélectionnez...</option>{COUNTRIES.map((country) => <option key={country}>{country}</option>)}</select></Field><Field label="Pays d'origine"><select name="originCountry" required defaultValue=""><option value="" disabled>Sélectionnez...</option>{COUNTRIES.map((country) => <option key={country}>{country}</option>)}</select></Field></div></>}<button className="btn btn-primary w-full" type="submit" disabled={loading}>{loading ? "Connexion..." : mode === "login" ? "Se connecter" : "Créer mon compte"}</button></form></div></div>; }

function Metric({ icon, number, label, tone = "blue" }: { icon: string; number: number; label: string; tone?: string }) { const colors: Record<string, string> = { blue: "bg-slate-100 text-ink", green: "bg-emerald-50 text-emerald-700", gold: "bg-amber-50 text-amber-700", red: "bg-red-50 text-red" }; return <div className="rounded-xl border bg-white p-4 shadow-sm" style={{ borderColor: "var(--line)" }}><span className={`mb-4 flex h-9 w-9 items-center justify-center rounded-lg text-lg ${colors[tone]}`}>{icon}</span><b className="block text-2xl">{number}</b><span className="text-xs uppercase tracking-wide text-slate-light">{label}</span></div>; }
function Empty({ icon, heading, text }: { icon: string; heading: string; text: string }) { return <div className="flex min-h-[230px] flex-col items-center justify-center px-5 text-center"><span className="mb-3 flex h-14 w-14 items-center justify-center rounded-lg bg-slate-100 text-3xl text-slate-light">{icon}</span><b>{heading}</b><p className="mt-1 max-w-sm text-sm text-slate-light">{text}</p></div>; }
function Home({ user, applications, counts, onView }: { user: User; applications: Application[]; counts: { total: number; done: number; active: number; refused: number }; onView: (view: View) => void }) { return <div><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Espace étudiant</p><h1 className="mt-2 text-3xl sm:text-4xl">Bonjour, {user.firstName} <span className="text-2xl">👋</span></h1><p className="mt-1 text-sm text-slate">Gérez vos demandes et suivez l&apos;avancement de vos dossiers.</p></div><button onClick={() => onView("nouvelle")} className="btn btn-primary btn-sm">＋ Nouvelle demande</button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon="▤" number={counts.total} label="Total demandes" /><Metric icon="✓" number={counts.done} label="Demandes finalisées" tone="green" /><Metric icon="◷" number={counts.active} label="En cours" tone="gold" /><Metric icon="×" number={counts.refused} label="Refusées" tone="red" /></div><section className="mt-7 overflow-hidden rounded-xl border bg-white" style={{ borderColor: "var(--line)" }}><div className="flex items-center justify-between border-b px-5 py-4" style={{ borderColor: "var(--line)" }}><h2 className="text-base">Mes demandes récentes</h2><button onClick={() => onView("demandes")} className="text-sm font-semibold text-red">Voir tout →</button></div>{applications.length === 0 ? <Empty icon="▤" heading="Aucune demande" text="Déposez votre première demande pour commencer votre accompagnement." /> : <div className="divide-y">{applications.slice(0, 4).map((application) => <div key={application.id} className="flex flex-wrap items-center justify-between gap-3 px-5 py-4"><div><b className="block text-sm">{types[application.type] ?? application.type}</b><span className="text-xs text-slate-light">{application.reference} · {date(application.createdAt)}</span></div><span className="status-pill status-wait">{statuses[application.status] ?? application.status}</span></div>)}</div>}</section></div>; }
function Heading({ heading, text, back }: { heading: string; text: string; back: () => void }) { return <div className="mb-7"><button onClick={back} className="mb-4 text-sm text-slate hover:text-ink">← Retour</button><h1 className="text-3xl sm:text-4xl">{heading}</h1><p className="mt-1 text-sm text-slate">{text}</p></div>; }

function Demandes({ applications, onView }: { applications: Application[]; onView: (view: View) => void }) { const [query, setQuery] = useState(""); const [status, setStatus] = useState("ALL"); const [type, setType] = useState("ALL"); const filtered = useMemo(() => applications.filter((item) => `${item.reference} ${item.type}`.toLowerCase().includes(query.toLowerCase()) && (status === "ALL" || item.status === status) && (type === "ALL" || item.type === type)), [applications, query, status, type]); return <div><Heading heading="Mes demandes" text="Historique complet de toutes vos demandes de services." back={() => onView("dashboard")} /><div className="mb-4 grid gap-3 md:grid-cols-[1fr_180px_150px]"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="⌕ Rechercher par référence, type..." className="rounded-lg border bg-white px-4 py-3 text-sm" /><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border bg-white px-3 py-3 text-sm"><option value="ALL">Tous les statuts</option>{Object.entries(statuses).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><select value={type} onChange={(event) => setType(event.target.value)} className="rounded-lg border bg-white px-3 py-3 text-sm"><option value="ALL">Tous les types</option>{Object.entries(types).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><div className="overflow-hidden rounded-xl border bg-white" style={{ borderColor: "var(--line)" }}>{filtered.length === 0 ? <Empty icon="▤" heading="Aucune demande trouvée" text="Modifiez vos filtres ou créez une nouvelle demande." /> : <>{filtered.map((item) => <div key={item.id} className="grid gap-2 border-b px-5 py-4 sm:grid-cols-4 sm:items-center"><b className="text-sm">{types[item.type] ?? item.type}</b><span className="text-sm text-slate">{item.reference}</span><span className="text-sm text-slate">{date(item.createdAt)}</span><span className="status-pill status-wait w-fit">{statuses[item.status] ?? item.status}</span></div>)}</>}</div></div>; }

function NewRequest({ token, onDone }: { token: string | null; onDone: () => void }) { const [loading, setLoading] = useState(false); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); const form = event.currentTarget; const type = (form.elements.namedItem("type") as HTMLSelectElement).value; const remarque = (form.elements.namedItem("remarque") as HTMLTextAreaElement).value; try { await apiRequest("/applications", { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: JSON.stringify({ type, formData: { remarque } }) }); showToast("Demande créée avec succès ✓"); onDone(); } catch (reason) { showToast(reason instanceof Error ? reason.message : "Erreur lors de la création"); } finally { setLoading(false); } } return <div><Heading heading="Nouvelle demande" text="Choisissez le type de demande que vous souhaitez déposer." back={onDone} /><div className="mb-7 grid gap-4 md:grid-cols-3">{["ADL", "AVI", "CAMPUS_FRANCE"].map((type) => <div key={type} className="rounded-xl border bg-white p-6 text-center" style={{ borderColor: "var(--line)" }}><span className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-red-50 text-2xl text-red">{type === "ADL" ? "⌂" : type === "AVI" ? "▤" : "⌁"}</span><b className="block">{types[type]}</b><span className="mt-1 block text-xs text-slate-light">{type === "ADL" ? "Attestation de logement" : type === "AVI" ? "Attestation de virement irrévocable" : "Accompagnement aux études"}</span></div>)}</div><form onSubmit={submit} className="max-w-2xl rounded-xl border bg-white p-5" style={{ borderColor: "var(--line)" }}><div className="field mb-4"><label>Type de demande</label><select name="type" defaultValue="ADL"><option value="ADL">ADL — Attestation de logement</option><option value="AVI">AVI — Attestation de virement irrévocable</option><option value="CAMPUS_FRANCE">Campus France</option></select></div><div className="field mb-5"><label>Précisions utiles</label><textarea name="remarque" placeholder="Ajoutez une remarque pour notre équipe..." /></div><button className="btn btn-primary" disabled={loading}>{loading ? "Envoi..." : "Créer la demande"}</button></form></div>; }

function Documents({ applications, token, onUploaded }: { applications: Application[]; token: string | null; onUploaded: () => void }) { const [loading, setLoading] = useState(false); const documents = applications.flatMap((application) => application.documents.map((document) => ({ ...document, reference: application.reference }))); async function upload(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const applicationId = (form.elements.namedItem("applicationId") as HTMLSelectElement).value; const file = (form.elements.namedItem("file") as HTMLInputElement).files?.[0]; if (!file || !applicationId) return; setLoading(true); const body = new FormData(); body.append("file", file); try { await apiRequest(`/applications/${applicationId}/documents`, { method: "POST", headers: { Authorization: `Bearer ${token}` }, body }); showToast("Document ajouté ✓"); form.reset(); onUploaded(); } catch (reason) { showToast(reason instanceof Error ? reason.message : "Téléversement impossible"); } finally { setLoading(false); } } return <div><Heading heading="Mes documents" text="Tous les documents soumis pour vos demandes." back={() => window.scrollTo(0, 0)} /><div className="mb-5 rounded-xl border bg-white p-5" style={{ borderColor: "var(--line)" }}><h2 className="mb-4 text-base">Ajouter un document</h2>{applications.length === 0 ? <p className="text-sm text-slate">Créez d&apos;abord une demande pour pouvoir déposer un document.</p> : <form onSubmit={upload} className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><select name="applicationId" required className="rounded-lg border bg-paper px-3 py-3 text-sm"><option value="">Choisir une demande</option>{applications.map((application) => <option key={application.id} value={application.id}>{application.reference} — {types[application.type]}</option>)}</select><input name="file" type="file" required className="rounded-lg border bg-paper px-3 py-2 text-sm" /><button className="btn btn-primary btn-sm" disabled={loading}>{loading ? "Envoi..." : "Ajouter"}</button></form>}</div><div className="overflow-hidden rounded-xl border bg-white" style={{ borderColor: "var(--line)" }}>{documents.length === 0 ? <Empty icon="▧" heading="Aucun document trouvé" text="Les documents de vos demandes apparaîtront ici." /> : documents.map((document) => <div key={document.id} className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div><b className="block text-sm">{document.name}</b><span className="text-xs text-slate-light">{document.reference} · {(document.size / 1024).toFixed(0)} Ko</span></div><span className="text-xs text-slate">{date(document.createdAt)}</span></div>)}</div></div>; }

function Payments({ applications }: { applications: Application[] }) { const payments = applications.flatMap((application) => application.payments.map((payment) => ({ ...payment, reference: application.reference, type: application.type }))); const paid = payments.filter((payment) => payment.status === "SUCCEEDED").reduce((sum, payment) => sum + payment.amount, 0); return <div><Heading heading="Mes paiements" text="Historique des paiements et reçus." back={() => window.scrollTo(0, 0)} /><div className="mb-6 grid gap-4 md:grid-cols-3"><Metric icon="✓" number={payments.filter((payment) => payment.status === "SUCCEEDED").length} label="Payées" tone="green" /><Metric icon="◷" number={payments.filter((payment) => payment.status === "PENDING").length} label="En attente" tone="gold" /><div className="rounded-xl border bg-white p-4" style={{ borderColor: "var(--line)" }}><span className="mb-4 flex h-9 w-9 items-center justify-center rounded-lg bg-slate-100 text-ink">€</span><b className="block text-2xl">{amount(paid, "EUR")}</b><span className="text-xs uppercase tracking-wide text-slate-light">Total payé</span></div></div><div className="overflow-hidden rounded-xl border bg-white" style={{ borderColor: "var(--line)" }}>{payments.length === 0 ? <Empty icon="▭" heading="Aucun paiement enregistré" text="Vos paiements apparaîtront ici après validation de votre dossier." /> : payments.map((payment) => <div key={payment.id} className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div><b className="block text-sm">{types[payment.type] ?? payment.type}</b><span className="text-xs text-slate-light">{payment.reference} · {date(payment.createdAt)}</span></div><b>{amount(payment.amount, payment.currency)}</b></div>)}</div></div>; }

function Profile({ user }: { user: User }) { return <div><Heading heading="Mon profil" text="Gérez vos informations personnelles et votre sécurité." back={() => window.scrollTo(0, 0)} /><div className="mb-5 flex items-center gap-4 rounded-xl border bg-white p-6" style={{ borderColor: "var(--line)" }}><div className="flex h-16 w-16 items-center justify-center rounded-full bg-red text-2xl font-bold text-white">{initials(user)}</div><div><h2 className="text-xl">{user.firstName} {user.lastName}</h2><p className="text-sm text-slate">{user.email}</p><span className="tag mt-2 inline-block">Étudiant</span></div></div><div className="rounded-xl border bg-white p-6" style={{ borderColor: "var(--line)" }}><h2 className="mb-5 border-b pb-4 text-base" style={{ borderColor: "var(--line)" }}>Informations personnelles</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="Prénom"><input value={user.firstName} readOnly /></Field><Field label="Nom"><input value={user.lastName} readOnly /></Field><Field label="Adresse email"><input value={user.email} readOnly /></Field><Field label="Téléphone"><input value={user.phone ?? "Non renseigné"} readOnly /></Field><Field label="Pays d'origine"><input value={user.originCountry ?? "Non renseigné"} readOnly /></Field><Field label="Pays de résidence"><input value={user.country ?? "Non renseigné"} readOnly /></Field></div><p className="mt-5 text-xs text-slate-light">La modification du profil sera disponible dès que l&apos;API de gestion du compte sera activée.</p></div></div>; }
function Messages({ token }: { token: string | null }) { const [messages, setMessages] = useState<{ id: string; subject: string; body: string; isRead: boolean; createdAt: string; sender: { firstName: string; lastName: string } }[]>([]); useEffect(() => { if (token) void apiRequest<typeof messages>("/auth/messages", { headers: { Authorization: `Bearer ${token}` } }).then(setMessages).catch(() => undefined); }, [token]); return <div><Heading heading="Mes messages" text="Les échanges envoyés par l'équipe GPI." back={() => window.scrollTo(0, 0)} /><div className="space-y-3">{messages.length === 0 ? <div className="rounded-xl border bg-white" style={{ borderColor: "var(--line)" }}><Empty icon="✉" heading="Aucun message" text="Les messages de l'équipe apparaîtront ici." /></div> : messages.map((message) => <article key={message.id} className={`rounded-xl border bg-white p-5 ${message.isRead ? "" : "border-red/30"}`}><div className="flex flex-wrap justify-between gap-3"><div><b>{message.subject}</b><p className="mt-1 text-xs text-slate">De {message.sender.firstName} {message.sender.lastName}</p></div><span className="text-xs text-slate-light">{date(message.createdAt)}</span></div><p className="mt-4 whitespace-pre-wrap text-sm text-slate">{message.body}</p></article>)}</div></div>; }
function Verification() { const [reference, setReference] = useState(""); const [result, setResult] = useState<string | null>(null); return <div><Heading heading="Vérificateur de document" text="Saisissez une référence pour contrôler l&apos;authenticité d&apos;un document." back={() => window.scrollTo(0, 0)} /><div className="mx-auto max-w-xl rounded-xl border bg-white p-6" style={{ borderColor: "var(--line)" }}><div className="field mb-4"><label>Code de vérification</label><input value={reference} onChange={(event) => setReference(event.target.value)} placeholder="Ex. GPI-AVI-2026-00123" /></div><button className="btn btn-primary w-full" onClick={() => setResult(reference.trim().toUpperCase().startsWith("GPI-") ? "Référence reconnue. La vérification définitive sera confirmée par l'API." : "Aucune référence ne correspond à cette saisie.")}>⌕ Vérifier l&apos;authenticité</button>{result && <p className="mt-5 rounded-lg border p-4 text-sm text-slate">{result}</p>}</div></div>; }

