"use client";

import { FormEvent, useEffect, useState } from "react";
import { api, Offer } from "@/lib/api";

const emptyForm = { title: "", company: "", location: "", type: "ALTERNANCE", duration: "", description: "", requirements: "", applyUrl: "", isPublished: false };

export default function OffersAdminPage() {
  const [offers, setOffers] = useState<Offer[]>([]);
  const [form, setForm] = useState(emptyForm);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const load = () => { void api.get<Offer[]>("/offers/admin/all").then(setOffers).catch((e: Error) => setError(e.message)); };
  useEffect(load, []);

  async function submit(event: FormEvent) {
    event.preventDefault(); setSaving(true); setError(""); setMessage("");
    try { await api.post<Offer>("/offers", form); setForm(emptyForm); setMessage("Offre enregistrée. Vous pouvez la publier ou la modifier ci-dessous."); load(); }
    catch (e) { setError(e instanceof Error ? e.message : "Impossible d’enregistrer l’offre."); }
    finally { setSaving(false); }
  }
  async function toggle(offer: Offer) { try { await api.patch(`/offers/${offer.id}`, { isPublished: !offer.isPublished }); load(); } catch (e) { setError(e instanceof Error ? e.message : "Mise à jour impossible."); } }
  async function remove(offer: Offer) { if (!window.confirm(`Supprimer « ${offer.title} » ?`)) return; try { await api.delete(`/offers/${offer.id}`); load(); } catch (e) { setError(e instanceof Error ? e.message : "Suppression impossible."); } }

  return <div className="mx-auto max-w-6xl"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-amber-700">Opportunités</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Offres d’alternance</h1><p className="mt-2 text-slate-600">Les offres publiées sont visibles immédiatement dans la rubrique publique.</p></div>
    {error && <p className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{message && <p className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{message}</p>}
    <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_1.15fr]"><form onSubmit={submit} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-lg font-semibold text-slate-950">Créer une offre</h2><div className="mt-5 space-y-4"><Field label="Intitulé" value={form.title} onChange={(title) => setForm({ ...form, title })} required /><label className="block text-sm font-medium text-slate-700">Catégorie<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as typeof form.type })} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100"><option value="ALTERNANCE">Alternance</option><option value="INTERNSHIP">Stage</option><option value="STUDENT_JOB">Job étudiant</option></select></label><div className="grid gap-4 sm:grid-cols-2"><Field label="Entreprise" value={form.company} onChange={(company) => setForm({ ...form, company })} required /><Field label="Ville / pays" value={form.location} onChange={(location) => setForm({ ...form, location })} required /></div><Field label="Durée" value={form.duration} onChange={(duration) => setForm({ ...form, duration })} placeholder="Ex. 12 mois" /><Area label="Description" value={form.description} onChange={(description) => setForm({ ...form, description })} required /><Area label="Profil recherché" value={form.requirements} onChange={(requirements) => setForm({ ...form, requirements })} /><Field label="Lien de candidature" value={form.applyUrl} onChange={(applyUrl) => setForm({ ...form, applyUrl })} placeholder="https://…" type="url" /><label className="flex items-center gap-3 text-sm text-slate-700"><input type="checkbox" checked={form.isPublished} onChange={(e) => setForm({ ...form, isPublished: e.target.checked })} className="size-4 accent-amber-500" />Publier dès maintenant</label><button disabled={saving} className="w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">{saving ? "Enregistrement…" : "Enregistrer l’offre"}</button></div></form>
      <section><h2 className="text-lg font-semibold text-slate-950">Offres existantes</h2><div className="mt-4 space-y-3">{offers.length === 0 ? <p className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500">Aucune offre créée pour l’instant.</p> : offers.map((offer) => <article key={offer.id} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex gap-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-950">{offer.title}</h3><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${offer.isPublished ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{offer.isPublished ? "Publiée" : "Brouillon"}</span></div><p className="mt-1 text-sm text-slate-600">{offer.company} · {offer.location}{offer.duration ? ` · ${offer.duration}` : ""}</p>{offer.isPublished && <p className="mt-2 text-xs font-medium text-amber-700">{offer.applicationClicks} clic{offer.applicationClicks > 1 ? "s" : ""} de candidature GPI{offer.lastClickedAt ? ` · dernier le ${new Date(offer.lastClickedAt).toLocaleDateString("fr-FR")}` : ""}</p>}</div><div className="flex shrink-0 gap-2"><button onClick={() => toggle(offer)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">{offer.isPublished ? "Retirer" : "Publier"}</button><button onClick={() => remove(offer)} className="rounded-lg px-3 py-2 text-xs font-semibold text-red-700 hover:bg-red-50">Supprimer</button></div></div></article>)}</div></section></div></div>;
}
function Field({ label, value, onChange, required, placeholder, type = "text" }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; placeholder?: string; type?: string }) { return <label className="block text-sm font-medium text-slate-700">{label}<input type={type} required={required} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100" /></label>; }
function Area({ label, value, onChange, required }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) { return <label className="block text-sm font-medium text-slate-700">{label}<textarea required={required} value={value} onChange={(e) => onChange(e.target.value)} rows={4} className="mt-1.5 w-full resize-y rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100" /></label>; }
