services:
  postgres:
    image: postgres:16-alpine
    container_name: plateforme-etudiante-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: plateforme_etudiante
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: plateforme-etudiante-mailpit
    restart: unless-stopped
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"

volumes:
  postgres_data:
